num1 = float(input("Digite um numero: "))
num2 = float(input("Digite um numero: "))
num3 = float(input("Digite um numero: "))
num4 = float(input("Digite um numero: "))
num5 = float(input("Digite um numero: "))
print(f"Dentro os numeros digitados o maior é {max(num1,num2,num3,num4,num5)}")